
# os: osx

# osx_image: xcode11.2
notifications:
  email:
    recipients:
      - humberto.a.sanchez.ii@gmail.com
    on_success: change # default: change
    on_failure: always # default: always

language: python

cache: pip

python:
  - "3.9.1"

before_install:
  - sudo apt-get update
#  - sudo apt-get -y install poppler
  - sudo apt install build-essential libpoppler-cpp-dev

# command to install dependencies
install:
  - pip install -r requirements.txt
#  - pip install fpdf2
#  - pip install Pillow
#  - pip install html-testRunner

# command to run tests
script: ${TRAVIS_BUILD_DIR}/scripts/runtests.sh -c
# script: pdftotext --help
