
version: '2.1'

orbs:
  python: circleci/python@2.1.1

workflows:
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

jobs:
  build:
    docker:
      - image: cimg/python:3.10
    executor: python/default
    steps:
      - checkout
      - run:
            name: Install library dependencies
            command: | 
                sudo apt-get update
                sudo apt-get install -y libpoppler-cpp-dev pkg-config
                sudo apt-get -y install poppler-utils
                pip install -r requirements.txt
      - run:
            name: run tests
            command: | 
              scripts/runtests.sh
